-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgavSUxpOdfW35fiLe
NlLG6Ypzg4Wk/Ywse7h3fOeXh5egCgYIKoZIzj0DAQehRANCAASKe8eyZSn+2N/7
A2YhdeNcAGTKyrGPiAaNsq/veujIcBbnp2aVhDrab0oMklxm4QgwhMyYob7JHM+i
3q3wF0Ta
-----END PRIVATE KEY-----